version: "3.9"
name: shared-postgres
services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
      - type: volume
        source: shared-postgres-data
        target: /var/lib/postgresql/data
    env_file: postgres.env
    security_opt:
      - no-new-privileges:true
    read_only: true
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080
    security_opt:
      - no-new-privileges:true
