version: "3.9"

name: shared-postgres

services:
  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
      - type: volume
        source: shared-postgres-data
        target: /var/lib/postgresql/data
    env_file: postgres.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080
